
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    command:
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=meteo_storage
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=meteo_storage
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app worker --loglevel=info
    depends_on:
      - db
      - redis

volumes:
  db_data: